/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UltraP;

/**
 *
 * @author ELITEBOOK
 */
public class SeleccionOrdenPokemon extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SeleccionOrdenPokemon.class.getName());

    /**
     * Creates new form SeleccionOrdenPokemon
     */
    public SeleccionOrdenPokemon() {
        initComponents();
    }
    private String nombrePoke1;
    private String nombrePoke2;
    private String nombrePoke3;
    private String nombreEntrenador;

    SeleccionOrdenPokemon(String nombre, String poke1, String poke2, String poke3) {
        initComponents();
        this.nombreEntrenador = nombre;
        this.nombrePoke1 = poke1;
        this.nombrePoke2 = poke2;
        this.nombrePoke3 = poke3;

        ListaPokemonesDisponibles.setText("Poknmon 1: " + poke1 + "\nPokemon 2: " + poke2 + "\nPokemon 3: " + poke3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TercerPokemonIMG = new javax.swing.JLabel();
        PrimerPokemonIMG = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        SegundoPokemonIMG = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaPokemonesDisponibles = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        Mensaje = new javax.swing.JTextField();
        PrimerPokemon = new javax.swing.JTextField();
        SegundoPokemon = new javax.swing.JTextField();
        TercerPokemon = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("SEGUNDO POKEMON");

        jLabel4.setText("TERCER POKEMON");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("ESCRIBE EL ORDEN DE TUS POKEMONES");

        ListaPokemonesDisponibles.setColumns(20);
        ListaPokemonesDisponibles.setRows(5);
        jScrollPane1.setViewportView(ListaPokemonesDisponibles);

        jButton1.setText("JUGAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        PrimerPokemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrimerPokemonActionPerformed(evt);
            }
        });

        SegundoPokemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SegundoPokemonActionPerformed(evt);
            }
        });

        TercerPokemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TercerPokemonActionPerformed(evt);
            }
        });

        jLabel2.setText("PRIMER POKEMON");

        jMenu2.setText("ELIGE TU POKEMON");

        jMenuItem3.setText("Seleccion Pokemon");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("ELIGE TU PERSONAJE");

        jMenuItem4.setText("Seleccion Entrenador");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        jMenu5.setText("ELIGE EL ORDEN DE TUS POKEMON");

        jMenuItem5.setText("Seleccion del Orden de tus Pokemones");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem5);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(jLabel1)
                .addGap(265, 265, 265))
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel2)
                .addGap(155, 155, 155)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(161, 161, 161))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PrimerPokemon, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addComponent(SegundoPokemon, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addComponent(TercerPokemon, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PrimerPokemonIMG)
                        .addGap(54, 54, 54)
                        .addComponent(SegundoPokemonIMG)
                        .addGap(34, 34, 34)
                        .addComponent(TercerPokemonIMG))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(Mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(93, 93, 93))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1)
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SegundoPokemon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PrimerPokemon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TercerPokemon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PrimerPokemonIMG)
                            .addComponent(SegundoPokemonIMG)
                            .addComponent(TercerPokemonIMG))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)))
                .addComponent(jButton1)
                .addContainerGap(241, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String p1 = PrimerPokemon.getText().trim();
        String p2 = SegundoPokemon.getText().trim();
        String p3 = TercerPokemon.getText().trim();

        if (p1.isEmpty() || p2.isEmpty() || p3.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Escribe los 3 Pokémon en orden");
            return;
        }

        BatallaUI ventana = new BatallaUI(nombreEntrenador, p1, p2, p3);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PrimerPokemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrimerPokemonActionPerformed
        String escrito = PrimerPokemon.getText().trim();

        if (escrito.equalsIgnoreCase(nombrePoke1)
                || escrito.equalsIgnoreCase(nombrePoke2)
                || escrito.equalsIgnoreCase(nombrePoke3)) {

            String ruta = "/proyectopokemon/Imagenes/" + escrito.toLowerCase() + ".png";
            PrimerPokemonIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource(ruta)));

        }
    }//GEN-LAST:event_PrimerPokemonActionPerformed

    private void SegundoPokemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SegundoPokemonActionPerformed
        String escrito = SegundoPokemon.getText().trim();

        if (escrito.equalsIgnoreCase(nombrePoke1)
                || escrito.equalsIgnoreCase(nombrePoke2)
                || escrito.equalsIgnoreCase(nombrePoke3)) {

            String ruta = "/proyectopokemon/Imagenes/" + escrito.toLowerCase() + ".png";
            SegundoPokemonIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource(ruta)));

        }
    }//GEN-LAST:event_SegundoPokemonActionPerformed

    private void TercerPokemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TercerPokemonActionPerformed
        String escrito = TercerPokemon.getText().trim();

        if (escrito.equalsIgnoreCase(nombrePoke1)
                || escrito.equalsIgnoreCase(nombrePoke2)
                || escrito.equalsIgnoreCase(nombrePoke3)) {

            String ruta = "/proyectopokemon/Imagenes/" + escrito.toLowerCase() + ".png";
            TercerPokemonIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource(ruta)));

        }
    }//GEN-LAST:event_TercerPokemonActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        SeleccionPokemon mostrar = new SeleccionPokemon();
        mostrar.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        SeleccionEntrenador mostrar = new SeleccionEntrenador();
        mostrar.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        SeleccionOrdenPokemon mostrar = new SeleccionOrdenPokemon();
        mostrar.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeleccionOrdenPokemon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ListaPokemonesDisponibles;
    private javax.swing.JTextField Mensaje;
    private javax.swing.JTextField PrimerPokemon;
    private javax.swing.JLabel PrimerPokemonIMG;
    private javax.swing.JTextField SegundoPokemon;
    private javax.swing.JLabel SegundoPokemonIMG;
    private javax.swing.JTextField TercerPokemon;
    private javax.swing.JLabel TercerPokemonIMG;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
