/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UltraP;

/**
 *
 * @author ELITEBOOK
 */
public class SeleccionPokemon extends javax.swing.JFrame {
    
    private String nombreEntrenador; 
    

    /**
     * Creates new form SeleccionPokemon
     */
    public SeleccionPokemon() {
        initComponents();
  
    }
    
    public SeleccionPokemon(String nombre) {
        initComponents();
        this.nombreEntrenador = nombre;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        VaporeonIMG = new javax.swing.JLabel();
        CacturneIMG = new javax.swing.JLabel();
        Vaporeon = new javax.swing.JCheckBox();
        Cacturne = new javax.swing.JCheckBox();
        CharizardIMG = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        UmbreonIMG = new javax.swing.JLabel();
        Mensaje = new javax.swing.JTextField();
        BotonFinalizar = new javax.swing.JButton();
        Charizard = new javax.swing.JCheckBox();
        Umbreon = new javax.swing.JCheckBox();
        BlazikenIMG = new javax.swing.JLabel();
        SkarmoryIMG = new javax.swing.JLabel();
        Blaziken = new javax.swing.JCheckBox();
        Skarmory = new javax.swing.JCheckBox();
        PiplupIMG = new javax.swing.JLabel();
        RaikouIMG = new javax.swing.JLabel();
        Piplup = new javax.swing.JCheckBox();
        Raikou = new javax.swing.JCheckBox();
        SnorlaxIMG = new javax.swing.JLabel();
        GardevoirIMG = new javax.swing.JLabel();
        Snorlax = new javax.swing.JCheckBox();
        Gardevoir = new javax.swing.JCheckBox();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();

        jMenu2.setText("ELIGE TU POKEMON");

        jMenuItem3.setText("Seleccion Pokemon");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("ELIGE TU PERSONAJE");

        jMenuItem4.setText("Seleccion Entrenador");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        jMenu5.setText("ELIGE EL ORDEN DE TUS POKEMON");

        jMenuItem5.setText("Seleccion del Orden de tus Pokemones");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem5);

        jMenuBar1.add(jMenu5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Vaporeon.setText("VAPOREON");
        Vaporeon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VaporeonActionPerformed(evt);
            }
        });

        Cacturne.setText("CACTURNE");
        Cacturne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CacturneActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("ELIGE 3 POKEMONES");

        BotonFinalizar.setText("FINALIZAR");
        BotonFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonFinalizarActionPerformed(evt);
            }
        });

        Charizard.setText("CHARIZARD");
        Charizard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CharizardActionPerformed(evt);
            }
        });

        Umbreon.setText("UMBREON");
        Umbreon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UmbreonActionPerformed(evt);
            }
        });

        Blaziken.setText("BLAZIKEN");
        Blaziken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlazikenActionPerformed(evt);
            }
        });

        Skarmory.setText("SKARMORY");
        Skarmory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SkarmoryActionPerformed(evt);
            }
        });

        Piplup.setText("PIPLUP");
        Piplup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PiplupActionPerformed(evt);
            }
        });

        Raikou.setText("RAIKOU");
        Raikou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RaikouActionPerformed(evt);
            }
        });

        Snorlax.setText("SNORLAX");
        Snorlax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SnorlaxActionPerformed(evt);
            }
        });

        Gardevoir.setText("GARDEVOIR");
        Gardevoir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GardevoirActionPerformed(evt);
            }
        });

        jMenu4.setText("ELIGE TU POKEMON");

        jMenuItem6.setText("Seleccion Pokemon");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuBar2.add(jMenu4);

        jMenu6.setText("ELIGE TU PERSONAJE");

        jMenuItem7.setText("Seleccion Entrenador");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem7);

        jMenuBar2.add(jMenu6);

        jMenu7.setText("ELIGE EL ORDEN DE TUS POKEMON");

        jMenuItem8.setText("Seleccion del Orden de tus Pokemones");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem8);

        jMenuBar2.add(jMenu7);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(CharizardIMG)
                                            .addComponent(Charizard))
                                        .addGap(74, 74, 74)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(BlazikenIMG)
                                            .addComponent(Blaziken)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Umbreon)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(23, 23, 23)
                                                .addComponent(UmbreonIMG)))
                                        .addGap(89, 89, 89)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Skarmory)
                                            .addComponent(SkarmoryIMG))))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(63, 63, 63)
                                        .addComponent(Piplup))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(74, 74, 74)
                                        .addComponent(PiplupIMG))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(63, 63, 63)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(RaikouIMG)
                                            .addComponent(Raikou)))))
                            .addComponent(Mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Gardevoir)
                                            .addComponent(GardevoirIMG)))
                                    .addComponent(SnorlaxIMG, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(VaporeonIMG))
                                    .addComponent(Vaporeon)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(CacturneIMG)
                                        .addComponent(Cacturne)
                                        .addComponent(BotonFinalizar))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(Snorlax))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addComponent(jLabel1)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(CharizardIMG)
                        .addComponent(PiplupIMG, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(SnorlaxIMG, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(VaporeonIMG, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(BlazikenIMG))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Charizard)
                    .addComponent(Blaziken)
                    .addComponent(Piplup)
                    .addComponent(Snorlax)
                    .addComponent(Vaporeon))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(UmbreonIMG)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(RaikouIMG)
                                .addComponent(SkarmoryIMG))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(CacturneIMG)
                                    .addComponent(GardevoirIMG))
                                .addGap(2, 2, 2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Gardevoir)
                    .addComponent(Raikou)
                    .addComponent(Cacturne)
                    .addComponent(Skarmory)
                    .addComponent(Umbreon))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonFinalizar)
                    .addComponent(Mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(241, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VaporeonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VaporeonActionPerformed
        if (Vaporeon.isSelected()) {
            int count = 0;
            if (Charizard.isSelected()) {
                count = count + 1;
            }
            if (Blaziken.isSelected()) {
                count = count + 1;
            }
            if (Piplup.isSelected()) {
                count = count + 1;
            }
            if (Snorlax.isSelected()) {
                count = count + 1;
            }
            if (Vaporeon.isSelected()) {
                count = count + 1;
            }
            if (Umbreon.isSelected()) {
                count = count + 1;
            }
            if (Skarmory.isSelected()) {
                count = count + 1;
            }
            if (Raikou.isSelected()) {
                count = count + 1;
            }
            if (Gardevoir.isSelected()) {
                count = count + 1;
            }
            if (Cacturne.isSelected()) {
                count = count + 1;
            }

            if (count > 3) {
                Vaporeon.setSelected(false);
                Mensaje.setText("Solo puedes seleccionar 3 pokemones");
            }
        }
    }//GEN-LAST:event_VaporeonActionPerformed

    private void CacturneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CacturneActionPerformed
        if (Cacturne.isSelected()) {
            int count = 0;
            if (Charizard.isSelected()) {
                count = count + 1;
            }
            if (Blaziken.isSelected()) {
                count = count + 1;
            }
            if (Piplup.isSelected()) {
                count = count + 1;
            }
            if (Snorlax.isSelected()) {
                count = count + 1;
            }
            if (Vaporeon.isSelected()) {
                count = count + 1;
            }
            if (Umbreon.isSelected()) {
                count = count + 1;
            }
            if (Skarmory.isSelected()) {
                count = count + 1;
            }
            if (Raikou.isSelected()) {
                count = count + 1;
            }
            if (Gardevoir.isSelected()) {
                count = count + 1;
            }
            if (Cacturne.isSelected()) {
                count = count + 1;
            }

            if (count > 3) {
                Cacturne.setSelected(false);
                Mensaje.setText("Solo puedes seleccionar 3 pokemones");
            }
        }
    }//GEN-LAST:event_CacturneActionPerformed

    private void BotonFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonFinalizarActionPerformed
        String poke1 = "", poke2 = "", poke3 = "";
        int i = 0;

        if (Charizard.isSelected()) {
            if (i == 0) {
                poke1 = "Charizard";
            } else if (i == 1) {
                poke2 = "Charizard";
            } else if (i == 2) {
                poke3 = "Charizard";
            }
            i=i+1;
        }
        if (Blaziken.isSelected()) {
            if (i == 0) {
                poke1 = "Blaziken";
            } else if (i == 1) {
                poke2 = "Blaziken";
            } else if (i == 2) {
                poke3 = "Blaziken";
            }
            i=i+1;
        }
        if (Piplup.isSelected()) {
            if (i == 0) {
                poke1 = "Piplup";
            } else if (i == 1) {
                poke2 = "Piplup";
            } else if (i == 2) {
                poke3 = "Piplup";
            }
            i=i+1;
        }
        if (Snorlax.isSelected()) {
            if (i == 0) {
                poke1 = "Snorlax";
            } else if (i == 1) {
                poke2 = "Snorlax";
            } else if (i == 2) {
                poke3 = "Snorlax";
            }
            i=i+1;
        }
        if (Vaporeon.isSelected()) {
            if (i == 0) {
                poke1 = "Vaporeon";
            } else if (i == 1) {
                poke2 = "Vaporeon";
            } else if (i == 2) {
                poke3 = "Vaporeon";
            }
            i=i+1;
        }
        if (Umbreon.isSelected()) {
            if (i == 0) {
                poke1 = "Umbreon";
            } else if (i == 1) {
                poke2 = "Umbreon";
            } else if (i == 2) {
                poke3 = "Umbreon";
            }
            i=i+1;
        }
        if (Skarmory.isSelected()) {
            if (i == 0) {
                poke1 = "Skarmory";
            } else if (i == 1) {
                poke2 = "Skarmory";
            } else if (i == 2) {
                poke3 = "Skarmory";
            }
            i=i+1;
        }
        if (Raikou.isSelected()) {
            if (i == 0) {
                poke1 = "Raikou";
            } else if (i == 1) {
                poke2 = "Raikou";
            } else if (i == 2) {
                poke3 = "Raikou";
            }
            i=i+1;
        }
        if (Gardevoir.isSelected()) {
            if (i == 0) {
                poke1 = "Gardevoir";
            } else if (i == 1) {
                poke2 = "Gardevoir";
            } else if (i == 2) {
                poke3 = "Gardevoir";
            }
            i=i+1;
        }
        if (Cacturne.isSelected()) {
            if (i == 0) {
                poke1 = "Cacturne";
            } else if (i == 1) {
                poke2 = "Cacturne";
            } else if (i == 2) {
                poke3 = "Cacturne";
            }
            i=i+1;
        }

        SeleccionOrdenPokemon ventana = new SeleccionOrdenPokemon(nombreEntrenador, poke1, poke2, poke3);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotonFinalizarActionPerformed

    private void CharizardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CharizardActionPerformed
        if (Charizard.isSelected()) {
            int count = 0;
            if (Charizard.isSelected()) {
                count = count + 1;
            }
            if (Blaziken.isSelected()) {
                count = count + 1;
            }
            if (Piplup.isSelected()) {
                count = count + 1;
            }
            if (Snorlax.isSelected()) {
                count = count + 1;
            }
            if (Vaporeon.isSelected()) {
                count = count + 1;
            }
            if (Umbreon.isSelected()) {
                count = count + 1;
            }
            if (Skarmory.isSelected()) {
                count = count + 1;
            }
            if (Raikou.isSelected()) {
                count = count + 1;
            }
            if (Gardevoir.isSelected()) {
                count = count + 1;
            }
            if (Cacturne.isSelected()) {
                count = count + 1;
            }

            if (count > 3) {
                Charizard.setSelected(false);
                Mensaje.setText("Solo puedes seleccionar 3 pokemones");
            }
        }
    }//GEN-LAST:event_CharizardActionPerformed

    private void UmbreonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UmbreonActionPerformed
        if (Umbreon.isSelected()) {
            int count = 0;
            if (Charizard.isSelected()) {
                count = count + 1;
            }
            if (Blaziken.isSelected()) {
                count = count + 1;
            }
            if (Piplup.isSelected()) {
                count = count + 1;
            }
            if (Snorlax.isSelected()) {
                count = count + 1;
            }
            if (Vaporeon.isSelected()) {
                count = count + 1;
            }
            if (Umbreon.isSelected()) {
                count = count + 1;
            }
            if (Skarmory.isSelected()) {
                count = count + 1;
            }
            if (Raikou.isSelected()) {
                count = count + 1;
            }
            if (Gardevoir.isSelected()) {
                count = count + 1;
            }
            if (Cacturne.isSelected()) {
                count = count + 1;
            }

            if (count > 3) {
                Umbreon.setSelected(false);
                Mensaje.setText("Solo puedes seleccionar 3 pokemones");
            }
        }
    }//GEN-LAST:event_UmbreonActionPerformed

    private void BlazikenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlazikenActionPerformed
        if (Blaziken.isSelected()) {
            int count = 0;
            if (Charizard.isSelected()) {
                count = count + 1;
            }
            if (Blaziken.isSelected()) {
                count = count + 1;
            }
            if (Piplup.isSelected()) {
                count = count + 1;
            }
            if (Snorlax.isSelected()) {
                count = count + 1;
            }
            if (Vaporeon.isSelected()) {
                count = count + 1;
            }
            if (Umbreon.isSelected()) {
                count = count + 1;
            }
            if (Skarmory.isSelected()) {
                count = count + 1;
            }
            if (Raikou.isSelected()) {
                count = count + 1;
            }
            if (Gardevoir.isSelected()) {
                count = count + 1;
            }
            if (Cacturne.isSelected()) {
                count = count + 1;
            }

            if (count > 3) {
                Blaziken.setSelected(false);
                Mensaje.setText("Solo puedes seleccionar 3 pokemones");
            }
        }
    }//GEN-LAST:event_BlazikenActionPerformed

    private void SkarmoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SkarmoryActionPerformed
        if (Skarmory.isSelected()) {
            int count = 0;
            if (Charizard.isSelected()) {
                count = count + 1;
            }
            if (Blaziken.isSelected()) {
                count = count + 1;
            }
            if (Piplup.isSelected()) {
                count = count + 1;
            }
            if (Snorlax.isSelected()) {
                count = count + 1;
            }
            if (Vaporeon.isSelected()) {
                count = count + 1;
            }
            if (Umbreon.isSelected()) {
                count = count + 1;
            }
            if (Skarmory.isSelected()) {
                count = count + 1;
            }
            if (Raikou.isSelected()) {
                count = count + 1;
            }
            if (Gardevoir.isSelected()) {
                count = count + 1;
            }
            if (Cacturne.isSelected()) {
                count = count + 1;
            }

            if (count > 3) {
                Skarmory.setSelected(false);
                Mensaje.setText("Solo puedes seleccionar 3 pokemones");
            }
        }
    }//GEN-LAST:event_SkarmoryActionPerformed

    private void PiplupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PiplupActionPerformed
        if (Piplup.isSelected()) {
            int count = 0;
            if (Charizard.isSelected()) {
                count = count + 1;
            }
            if (Blaziken.isSelected()) {
                count = count + 1;
            }
            if (Piplup.isSelected()) {
                count = count + 1;
            }
            if (Snorlax.isSelected()) {
                count = count + 1;
            }
            if (Vaporeon.isSelected()) {
                count = count + 1;
            }
            if (Umbreon.isSelected()) {
                count = count + 1;
            }
            if (Skarmory.isSelected()) {
                count = count + 1;
            }
            if (Raikou.isSelected()) {
                count = count + 1;
            }
            if (Gardevoir.isSelected()) {
                count = count + 1;
            }
            if (Cacturne.isSelected()) {
                count = count + 1;
            }

            if (count > 3) {
                Piplup.setSelected(false);
                Mensaje.setText("Solo puedes seleccionar 3 pokemones");
            }
        }
    }//GEN-LAST:event_PiplupActionPerformed

    private void RaikouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RaikouActionPerformed
        if (Raikou.isSelected()) {
            int count = 0;
            if (Charizard.isSelected()) {
                count = count + 1;
            }
            if (Blaziken.isSelected()) {
                count = count + 1;
            }
            if (Piplup.isSelected()) {
                count = count + 1;
            }
            if (Snorlax.isSelected()) {
                count = count + 1;
            }
            if (Vaporeon.isSelected()) {
                count = count + 1;
            }
            if (Umbreon.isSelected()) {
                count = count + 1;
            }
            if (Skarmory.isSelected()) {
                count = count + 1;
            }
            if (Raikou.isSelected()) {
                count = count + 1;
            }
            if (Gardevoir.isSelected()) {
                count = count + 1;
            }
            if (Cacturne.isSelected()) {
                count = count + 1;
            }

            if (count > 3) {
                Raikou.setSelected(false);
                Mensaje.setText("Solo puedes seleccionar 3 pokemones");
            }
        }
    }//GEN-LAST:event_RaikouActionPerformed

    private void SnorlaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SnorlaxActionPerformed
        if (Snorlax.isSelected()) {
            int count = 0;
            if (Charizard.isSelected()) {
                count = count + 1;
            }
            if (Blaziken.isSelected()) {
                count = count + 1;
            }
            if (Piplup.isSelected()) {
                count = count + 1;
            }
            if (Snorlax.isSelected()) {
                count = count + 1;
            }
            if (Vaporeon.isSelected()) {
                count = count + 1;
            }
            if (Umbreon.isSelected()) {
                count = count + 1;
            }
            if (Skarmory.isSelected()) {
                count = count + 1;
            }
            if (Raikou.isSelected()) {
                count = count + 1;
            }
            if (Gardevoir.isSelected()) {
                count = count + 1;
            }
            if (Cacturne.isSelected()) {
                count = count + 1;
            }

            if (count > 3) {
                Snorlax.setSelected(false);
                Mensaje.setText("Solo puedes seleccionar 3 pokemones");
            }
        }
    }//GEN-LAST:event_SnorlaxActionPerformed

    private void GardevoirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GardevoirActionPerformed
        if (Gardevoir.isSelected()) {
            int count = 0;
            if (Charizard.isSelected()) {
                count = count + 1;
            }
            if (Blaziken.isSelected()) {
                count = count + 1;
            }
            if (Piplup.isSelected()) {
                count = count + 1;
            }
            if (Snorlax.isSelected()) {
                count = count + 1;
            }
            if (Vaporeon.isSelected()) {
                count = count + 1;
            }
            if (Umbreon.isSelected()) {
                count = count + 1;
            }
            if (Skarmory.isSelected()) {
                count = count + 1;
            }
            if (Raikou.isSelected()) {
                count = count + 1;
            }
            if (Gardevoir.isSelected()) {
                count = count + 1;
            }
            if (Cacturne.isSelected()) {
                count = count + 1;
            }

            if (count > 3) {
                Gardevoir.setSelected(false);
                Mensaje.setText("Solo puedes seleccionar 3 pokemones");
            }
        }
    }//GEN-LAST:event_GardevoirActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        SeleccionPokemon mostrar = new SeleccionPokemon();
        mostrar.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        SeleccionEntrenador mostrar = new SeleccionEntrenador();
        mostrar.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        SeleccionOrdenPokemon mostrar = new SeleccionOrdenPokemon();
        mostrar.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        SeleccionPokemon mostrar = new SeleccionPokemon();
        mostrar.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        SeleccionEntrenador mostrar = new SeleccionEntrenador();
        mostrar.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        SeleccionOrdenPokemon mostrar = new SeleccionOrdenPokemon();
        mostrar.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeleccionPokemon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Blaziken;
    private javax.swing.JLabel BlazikenIMG;
    private javax.swing.JButton BotonFinalizar;
    private javax.swing.JCheckBox Cacturne;
    private javax.swing.JLabel CacturneIMG;
    private javax.swing.JCheckBox Charizard;
    private javax.swing.JLabel CharizardIMG;
    private javax.swing.JCheckBox Gardevoir;
    private javax.swing.JLabel GardevoirIMG;
    private javax.swing.JTextField Mensaje;
    private javax.swing.JCheckBox Piplup;
    private javax.swing.JLabel PiplupIMG;
    private javax.swing.JCheckBox Raikou;
    private javax.swing.JLabel RaikouIMG;
    private javax.swing.JCheckBox Skarmory;
    private javax.swing.JLabel SkarmoryIMG;
    private javax.swing.JCheckBox Snorlax;
    private javax.swing.JLabel SnorlaxIMG;
    private javax.swing.JCheckBox Umbreon;
    private javax.swing.JLabel UmbreonIMG;
    private javax.swing.JCheckBox Vaporeon;
    private javax.swing.JLabel VaporeonIMG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    // End of variables declaration//GEN-END:variables
}
